version: '3.9'
services:
  backend:
    build: .
    ports: 
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db  
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambasador
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
